### ISSUE TITLE
Zoom not work.

### ISSUE THREAD

**Issue by AlexCernik** [likashefqet/react-native-image-zoom#6]
Hi, zoom not working on modal component on android.

**Comment by likashefqet** [comment]
# Usage with modals on Android
On Android React Native Gesture Handler does not work by default because modals are not located under React Native Root view in native hierarchy. To fix that, components need to be wrapped with gestureHandlerRootHOC (it's no-op on iOS and web).

[Check official statement here](https://docs.swmansion.com/react-native-gesture-handler/docs/#usage-with-modals-on-android)

For example:

```javascript
const ImageZoomInModal = gestureHandlerRootHOC(() => (
  <ImageZoom uri={imageUri}  />
);

export default function Example() {
  return (
    <Modal>
      <ImageZoomInModal />
    </Modal>
  );
}
```
